AWSTemplateFormatVersion: '2010-09-09'
Description: 'Sample application deployed by CI/CD pipeline'

Parameters:
  Environment:
    Type: String
    Description: Environment name
    Default: production
    AllowedValues:
      - development
      - staging
      - production

Resources:
  # Sample Lambda Function
  HelloWorldFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'hello-world-${Environment}'
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          exports.handler = async (event) => {
              console.log('Hello from Lambda!');
              return {
                  statusCode: 200,
                  body: JSON.stringify({
                      message: 'Hello World!',
                      environment: process.env.ENVIRONMENT,
                      timestamp: new Date().toISOString()
                  })
              };
          };
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CICD-Pipeline

  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'hello-world-lambda-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # CloudWatch Log Group
  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/hello-world-${Environment}'
      RetentionInDays: 7

Outputs:
  FunctionName:
    Description: Name of the Lambda function
    Value: !Ref HelloWorldFunction
    Export:
      Name: !Sub '${AWS::StackName}-FunctionName'
  
  FunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt HelloWorldFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionArn'
  
  Environment:
    Description: Environment name
    Value: !Ref Environment
